DROP TABLE "Employee" CASCADE;
DROP TABLE "EmployeeSkills" CASCADE;
DROP TABLE "LocationCompany" CASCADE;
DROP TABLE "LocationGroup" CASCADE;
DROP TABLE "LocationOffice" CASCADE;
DROP TABLE "LocationPhysical" CASCADE;
DROP TABLE "Skill" CASCADE;
DROP TABLE "SkillCategory" CASCADE;
DROP TABLE "ManagerLocationCompany" CASCADE;
DROP TABLE "ManagerLocationGroup" CASCADE;
DROP TABLE "ManagerLocationOffice" CASCADE;
DROP SEQUENCE "public".contractorseq;